name: wf-ci-development
on:
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
  steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: lint Html and CSS
      run: |
         npx htmlhint "**/*.html"
         npx stylelint "**/*.css"
    - name: Test build ops
      run: |
        npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./" 